<?php
/** @var \Monext\HyvaPayline\Block\PaylineWebPaymentCpt $block */
/** @var \Monext\HyvaPayline\Magewire\PaylineWebPayment $magewire */

?>

<div class="payment-method payline-payment-block"
     x-data="paylineCptWidgetComponent"
     data-token="<?= $magewire->getToken() ?>">

    <div class="payment-method-content">
        <div id="payline-widget-container" wire:ignore></div>
    </div>
</div>
