<?php
/**
 * @var $block \Monext\HyvaPayline\Block\Js\PaylineWebPaymentCpt
 *
 * WARNING: Only one script tag in this file, nonce is generated on the fly by \Monext\HyvaPayline\Block\Js\PaylineWebPaymentCpt::_toHtml
 */

?>
<script>
    function paylineCptRedirectComponent() {
        'use strict';
        return {
            init() {
                let contractsRedirect = document.getElementById('payline-contracts-redirect');
                contractsRedirect.addEventListener('change', async function () {
                    let selected = document.querySelector('input[name="payment[payline_payments_standard][contract_id]"]:checked');
                    if (selected !== null) {
                        await Magewire.find('checkout.payment.method.payline_web_payment_cpt').call('setAdditionalData', selected.value);
                    }
                });
            }
        };
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('paylineCptRedirectComponent', paylineCptRedirectComponent);
    }, { once: true });
</script>
