<?php
/** @var \Monext\HyvaPayline\Magewire\PaylineWebPaymentCpt $magewire */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Monext\HyvaPayline\Block\PaylineWebPaymentCpt $block */
?>
<div class="payment-method payline-payment-block">
    <div class="payment-method-content">
        <div id="payline-widget-container" ></div>
    </div>
    <script>
        'use strict';
        (function () {
            window.addEventListener('checkout:payment:method-activate', async event => {
                if (event.detail.method === "payline_web_payment_cpt") {
                    hyvaCheckout.payment.activate('payline_web_payment_cpt', {
                        initialize() {
                            this.loadHostedLib().then(() => {
                                if (!this.checkLoaded()) {
                                    const token = '<?= $escaper->escapeJs($magewire->getToken()); ?>';
                                    const context = {};
                                    WidgetApi.showWidget(context, token);
                                }
                            }).catch(() => {
                                // TODO : traiter erreur si loadHostedLib échoue
                                alert("Error while loading payment widget");
                            });
                        },
                        loadHostedLib() {
                            return new Promise((resolve, reject) => {
                                //--> Check if script is already in head
                                const widgetScriptHead = document.getElementById("widget-api-vanilla");
                                if (widgetScriptHead) {
                                    resolve();
                                } else {
                                    const script = document.createElement('script');
                                    script.src = '<?= $this->getViewFileUrl('Monext_Payline/js/widget-api-vanilla.js')?>';
                                    script.setAttribute('id', 'widget-api-vanilla');
                                    script.type = 'text/javascript';
                                    script.onload = () => {
                                        resolve();
                                    }
                                    script.onerror = () => {
                                        reject();
                                    }
                                    document.head.append(script);
                                }
                            });
                        },
                        checkLoaded: function () {
                            return document.body.contains(document.getElementById('PaylineWidget'));
                        },
                    });
                }
            });
        })();
    </script>
</div>
