<?php
/** @var \Monext\HyvaPayline\Magewire\Checkout\Payment\Method\PaylineWebPaymentCpt $magewire */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Monext\HyvaPayline\Block\PaylineWebPaymentCpt $block */

$config = $block->getConfig();
$contracts = $config['payline']['general']['contracts'];
?>
<div class="payment-method payline-payment-block">
    <div class="payment-method-content">
        <div>
            <span><?= $escaper->escapeHtml(__('You will be redirected on payline payment gateway after place order.')) ?></span>
        </div>
        <table id="payline-contracts" style="margin-bottom: 20px; border: none;">
            <tbody>
            <?php foreach ($contracts as $contract): ?>
                <tr>
                    <td style="width: 15%; vertical-align: middle; padding-bottom: 0;">
                        <input type="radio"
                               name="payment[payline_contract]"
                               class="radio"
                               id="<?= $contract['id'] ?>"
                               value="<?= $contract['number'] ?>"/>
                        <label for="<?= $contract['id'] ?>" class="label"><span><?= $contract['label'] ?></span></label>
                    </td>
                    <td style="vertical-align: middle; padding-bottom: 0;">
                        <img src="<?= $contract['logo'] ?>" alt="payment_method_logo_<?= $contract['id']?>"/>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script>
    'use strict';
    (function () {
        document.getElementById('payline-contracts').addEventListener('change', async function () {
            let selected = document.querySelector('input[name="payment[payline_contract]"]:checked');
            if(selected !== null) {
                await Magewire.find('checkout.payment.method.payline_web_payment_cpt').call('setAditionalData', selected.value);
            }
        });
    })();
</script>
