<?php
/**
 * @var \Monext\Payline\Block\Customer\Wallet $block
 */
?>
<?php if ($block->hasCustomerWallet()) : ?>
    <?php if ($block->isManageWebWalletInError()) : ?>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
            <span><?= $block->escapeHtml(__($block->getManageWebWalletErrorMessage())) ?></span>
        </div>
    <?php else : ?>
        <?php $config = $block->getManageWebWalletJsConfig(); ?>

        <div
            id="payline-widget-container"
            x-data="paylineWalletWidget({
                environment: '<?= $config['environment'] ?>',
                token: '<?= $config['token'] ?>',
                widgetDisplay: 'column',
                containerId: 'payline-widget-container'
            })"
            x-init="mountWidgetWithToken()"
            class="my-4"
        ></div>
        <script>
            function paylineWalletWidget(config) {
                return {
                    mountWidgetWithToken () {
                        this.loadHostedLib().then(() => {
                            WidgetApi.showWidget(config, config.token);
                        }).catch((error) => {
                            // TODO : Manage error
                            console.error(error);
                        });
                    },
                    loadHostedLib() {
                        return new Promise((resolve, reject) => {
                            //--> Check if script is already in head
                            const widgetScriptHead = document.getElementById("widget-api-vanilla");
                            if (widgetScriptHead) {
                                resolve();
                            } else {
                                const script = document.createElement('script');
                                script.src = '<?= $block->getViewFileUrl('Monext_Payline/js/widget-api-vanilla.js') ?>';
                                script.setAttribute('id', 'widget-api-vanilla');
                                script.type = 'text/javascript';
                                script.onload = () => {
                                    resolve();
                                }
                                script.onerror = () => {
                                    reject(new Error('Failed to load script : ' + script.src));
                                }
                                document.head.append(script);
                            }
                        });
                    }
                }
            }
        </script>
    <?php endif; ?>
<?php else : ?>
    <div class="bg-blue-100 border border-blue-300 text-blue-700 px-4 py-3 rounded">
        <span><?= __('You have no wallets.') ?></span>
    </div>
<?php endif; ?>
